### ISSUE TITLE
namespace conflict with start_parallel_*.py when installing QIIME and PICRUSt simultaneously

### ISSUE THREAD

**Issue by zaneveld** [picrust/picrust#157]
There is a namespace conflict where QIIME and PICRUSt share versions of start_parallel_*.py with small differences that could produce unexpected behavior.  This may or may not be an issue right now, but will likely become a big problem over time if left as is.

   The ideal solution would be to consolidate both into a common repository (pyqi?  PyCogent as a slightly awkward fallback?).   

    A temporary bandaid would be to just rename the PICRUSt parallel scripts by appending _picrust or the like to the end.

[hat tip to Douglas Rudd in the forum for identifying this issue]

**Comment by mlangill** [comment]
Fixed via PR #206 from @zaneveld
