### ISSUE TITLE
Documentation update: predict metagenomes NSTI values clarification

### ISSUE THREAD

**Issue by zaneveld** [picrust/picrust#160]
The current documentation for the -a option in predict metagenomes is a little unclear.  Since the pre-calculated files already have NSTI values available, we should update to explicitly state that you only need to rerun predict_traits.py for custom analysis.

**Comment by colinbrislawn** [comment]
Hi there.

I just stumbled across the forum post and found it very helpful. Indeed, the current documentation could clearly state that 'pre-calculated files already have NSTI values available' and 'you only need to rerun predict_traits.py for custom analysis.' Thanks to the discussion on the forum and clarfication from the devs, I'm making more progress. 

I'm interested in contributing documentation. Is this project / team accepting PRs?
