### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by audy** [picrust/picrust#168]
numpy==1.8.1
Cython==0.20.1
cogent==1.5.3
biom==1.3.1

For the sake of staying up-to-date.

**Comment by prehensilecode** [comment]
Without QIIME, the all_tests.py script passes all with the following installation: Python 2.7.9 with numpy 1.9.2, Cython 0.22, cogent 1.5.3, and biom 1.3.1.

I'm pretty sure it will be OK with Python 2.7.10.

**Comment by audy** [comment]
Obsolete.
