### ISSUE TITLE
PICRUSt broken with BIOM 2.0

### ISSUE THREAD

**Issue by stelllaras** [picrust/picrust#170]
The current PICRUSt version does not seem to work with the latest BIOM format (2.0). A quick look into the PICRUSt scripts verifies that it indeed relies on the old biom version.

**Comment by colinbrislawn** [comment]
I just used picrust on a HDF biom file! Looks like #197 closes this issue.

**Comment by wasade** [comment]
Yes, we need to get a release out soon. If you're interested, dev support
would be appreciated

**Comment by colinbrislawn** [comment]
I can test things, write basic documentation, and make conda recipes. If there is simple ways I can help, please feel free to @ me and I will take a shot at it.

**Comment by wasade** [comment]
Awesome, thank you!

**Comment by mlangill** [comment]
Fixed with version 1.1 release
