### ISSUE TITLE
Enable PICRUSt to be used with de-novo OTUs

### ISSUE THREAD

**Issue by mlangill** [picrust/picrust#182]
PICRUSt currently makes predictions based only on reference OTUs (those with matches within 97% of the greengenes database). Considering that "open-reference" picking is quickly becoming the default method for obtaining OTUs, it would be idea if PICRUSt could make predictions using all OTUs. 

[Note: this will be the first of many features on the road to PICRUSt 2.0]

**Comment by gavinmdouglas** [comment]
Implemented in PICRUSt2: https://github.com/picrust/picrust2
