### ISSUE TITLE
PICRUSt cannot work after update the QIIME 1.9

### ISSUE THREAD

**Issue by binma** [picrust/picrust#185]
Hi, I found the PICRUSt cannot work after I update the QIIME to 1.9 version. I use QIIME under Mac, and install the PICRUSt in macqiime environment.

**Comment by mlangill** [comment]
Now fixed!

**Comment by binma** [comment]
Hi Morgan,

That is great. Them I need not  convert biom into tsp before use PRICSt.

Thanks

Bin
