### ISSUE TITLE
Add GreenGenes 13.8 to Galaxy PICRUSt?

### ISSUE THREAD

**Issue by AmandaBirmingham** [picrust/picrust#187]
Hello,
I'm using the Galaxy PICRUSt install to examine an OTU table I generated with QIIME 1.9.1, which uses GreenGenes 13.8 as its default reference set.  At the "Normalize by Copy Number" step of PICRUSt, it asks me to pick the GreenGenes version to use, but the latest version available is 13.5.  Are there any plans to add 13.8?  I saw a past issue (from 2013) about adding newer GreenGenes versions, but it is marked as closed ...
Best,
Amanda

**Comment by wasade** [comment]
The OTU structure for Greengenes is identical between 13_5 and 13_8 so
there isn't a change here. The only difference between those versions is a
set of taxonomy annotation updates, but taxonomy is not taken into account
by PICRUSt

On Wed, Aug 19, 2015 at 1:44 PM, Amanda Birmingham <notifications@github.com

**Comment by zaneveld** [comment]
Thanks for the suggestion - based on Daniel's confirmation this seems like a resolved issue, so I'll go ahead and close it.
