### ISSUE TITLE
precalculated files unavailable; not downloaded in default installation

### ISSUE THREAD

**Issue by ksdiaz** [picrust/picrust#196]
None of PICRUSt's precalculated files are downloaded and so not installed.  When running metagenome_contributions.py errors for the cog, ko, 16S, and all precalculated files get thrown up, for example:
`IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/picrust/data/cog_13_5_precalculated.tab.gz'`

The files are not only missing, but the /usr/local/lib/python2.7/site-packages/picrust/data/ directory does not exist either and has to be created and files downloaded manually.  I downloaded all of the from SourceForge, as they are not available anywhere from PICRUSt develops, and the ftp links provided in the repository here throw up a "failed to change directory error" if one attempts to download via browser, and "No such directory 'picrust-references/picrust-1.0.0' " error via wget.  I output it to /usr/local/lib/python2.7/site-packages/picrust/data/  which does exist.

Update: The ftp links in the repository here and on the Picrust.github.io page should be ftp://ftp.microbio.me/pub/picrust-references/picrust-1.0.0/, not ftp://ftp.microbio.me//picrust-references/picrust-1.0.0/

**Comment by colinbrislawn** [comment]
Good catch on that FTP URL. I ran into that problem a few days ago too.

I'll try to fix that on the website... 

We could distribute the core data files (*precalculated.tab.gz) in another github repo, see [vsearch](https://github.com/torognes/vsearch) and [vsearch-data](https://github.com/torognes/vsearch-data) for an example of this.
