### ISSUE TITLE
Make a picrust conda recipe 

### ISSUE THREAD

**Issue by colinbrislawn** [picrust/picrust#199]
And put it on bioconda.

Looks like the dependencies are 
- R: gee, ape
- python: pip, numpy, scipy, cython, h5py, biom-format

Some of these are already on bioconda!

**Comment by gavinmdouglas** [comment]
Looks like someone has made a bioconda recipe: [https://anaconda.org/bioconda/picrust](https://anaconda.org/bioconda/picrust)

It would be better if the pre-calculated files were automatically downloaded for the user though as well. I think this could be added into the recipe.

**Comment by colinbrislawn** [comment]
Here is the source code for that recipe, created by @druvus 
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/picrust/ 

I think including the pre-calculate files is tricky because they are large. Keep in mind that while the conda recipe only includes commands to download these files, the final conda package needs to include full copies of them. That might make the conda package pretty large. 

@druvus, do you have any ideas on how best to distribute large, important databases associated with a conda package?

**Comment by druvus** [comment]
Sorry I didn't see this thread until now, 

I think it would better to seperate the code and db into different conda packages. The current bioconda package doesn't relly work out of the box as it doesn't include the precalculated files. I would like to have the option to set a custom path to pre-calculated files instead of forcing users to install it by the setup script. This way conda packages wouldn't be so huge and I guess the code base is updated more frequently than the pre-calculated files.

**Comment by colinbrislawn** [comment]
Thanks for the feedback @druvus. Your advice here is really helpful. 

Is the separation of packages something you could lead? I'm not sure how best to set that up. Perhaps a second package like `picrust-references` as a dependency of `picrust`?

The raw files needed are here. They have not been updated recently, but I'm not sure about the future.
ftp://ftp.microbio.me/pub/picrust-references/picrust-1.0.0/

**Comment by gavinmdouglas** [comment]
Thanks @druvus. Maybe adding in a couple of extra steps after the conda command on the anaconda page could be a fix for now? 

For instance the user could figure out the site-packages location ("SITE_PACKAGES_DIR" below) with this command:

    python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
    
Go to the picrust directory:  

    cd SITE_PACKAGES_DIR/picrust

Make a folder called "data"

    mkdir data

Download whichever pre-calculated files they want (for example):

    wget ftp://ftp.microbio.me/pub/picrust-references/picrust-1.0.0/16S_13_5_precalculated.tab.gz -O data/16S_13_5_precalculated.tab.gz

    wget ftp://ftp.microbio.me/pub/picrust-references/picrust-1.0.0/ko_13_5_precalculated.tab.gz -O data/ko_13_5_precalculated.tab.gz

This isn't ideal, but at least it would make the conda package functional.

**Comment by mortonjt** [comment]
@druvus @gavinmdouglas how crazy would it be to just include the wget commands within the `build.sh`

**Comment by colinbrislawn** [comment]
Wouldn't that end up including the databases in the conda package (what we trying to avoid)?

Is there a section that runs after the `conda install` has finished? This could make a copy on the local computer, while avoiding a copy in the package itself. Or perhaps we could at the `wget` command as a dependency check, which downloads the first time someone tries to run a script.

**Comment by druvus** [comment]
It would be preferred to have a function/script to download the files separately to the correct location. It would be possible to rewrite the `download_metaphlan2_db.py` in the bioconda metaphlan recipe to this task in a semi-automatic way. 

I have recently been a lot out of office but I will try to look into this next week.

**Comment by druvus** [comment]
@colinbrislawn @gavinmdouglas @mortonjt  
I have opened a PR at bioconda (bioconda/bioconda-recipes#5586) to include a version of PICRUST that contains the new download script added in #226 (using commit 6e7624d). Please take a look if you think it looks ok or do you prefer to release a new PICRUST version first?

**Comment by gavinmdouglas** [comment]
@druvus 
Thanks for opening that up - I am currently on vacation, but will release a new version when I return this week. I'll let you know when this is done!

**Comment by druvus** [comment]
@gavinmdouglas thanks! Enjoy your vacation.

**Comment by gavinmdouglas** [comment]
@druvus there is a new release now that includes ```download_picrust_files.py```. This should fix the bioconda install issues: users should just need to run this script after installing PICRUSt with the conda command.

**Comment by druvus** [comment]
@gavinmdouglas the latest version is now added to to bioconda so I think you can close this issue.

**Comment by gavinmdouglas** [comment]
Thanks a lot @druvus
