### ISSUE TITLE
Update the taxonomic and functional databases

### ISSUE THREAD

**Issue by omanor** [picrust/picrust#221]
Is there a plan to update the taxonomic database (i.e., GG) and/or the functional database (KEGG)? Both are from the time the paper was published, and I think that would be a great new feature :-)

Cheers,
Ohad

**Comment by gavinmdouglas** [comment]
Hey Ohad,

Yes that’s what I’m working on at the moment!


Best,

Gavin

**Comment by omanor** [comment]
That is great news Gavin, looking forward to using the updated databases!

Ohad

--
Ohad Manor, PhD
Bioinformatics Machine Learning Scientist
email: omanor@arivale.com
office: 206-981-5824
cell: 206-856-1430
[cid:image001.png@01D2F571.BB54C490]<https://www.arivale.com/>
Your Scientific Path to Wellness

Geekwire’s 2016 Startup of the Year<http://www.geekwire.com/2016/revealed-winners-2016-geekwire-awards/>

**Comment by gavinmdouglas** [comment]
Hi Igor,

I have updated the database files for picrust2 (https://github.com/picrust/picrust2), which is in alpha release right now. The files are not compatible with picrust1 since there is no longer a required link to Greengenes ids. A beta release is coming soon and you can follow that repository if you want to keep up to date.

Thanks,

Gavin

**Comment by msk33** [comment]
Dear Gavin,

I am really happy to hear that database for PICRUSt has been updated!
To make the most of PICRUSt2, I would like to know which reference database is used. Again IMG database? Or, is it based on some other public database?

Thank you in advance for your help,

**Comment by gavinmdouglas** [comment]
Hi Kaz,

Yes the default PICRUSt2 databases are based on IMG genome annotations and 16S sequences from those genomes.


Best,

Gavin
