### ISSUE TITLE
update install documentation to recommend conda

### ISSUE THREAD

**Issue by colinbrislawn** [picrust/picrust#234]
Now that PICRUSt is on conda, what's the recommended way to install it? The web page does not list conda as an option, so I'm not sure if I should recomend this to users.

Thank you for the update. If a conda install is not wanted, feel free to close this issue.

Thanks,
Colin

**Comment by gavinmdouglas** [comment]
Hi Colin,

Thanks for the reminder - I changed the install page to now recommend installing with conda.
