### ISSUE TITLE
compare_biom.py ValueError: too many values to unpack

### ISSUE THREAD

**Issue by apascualgarcia** [picrust/picrust#257]
Hello, I asked the following in the user's list but I think it should be better reported here.

I'm comparing metagenomic experiments with PiCRUST predictions using compare_biom.py and I get the following error:
`
~/pkg/anaconda3/envs/picrust/lib/python2.7/site-packages/biom/table.py", line 4679, in list_list_to_sparse
    rows, cols, values = zip(*data)
ValueError: too many values to unpack
`

Both biom tables are hdf5. To discard that there is any problem with them, I run the script considering for both "observed" and "expected" tables the same table. Doing this with both the metagenomics experiments table or with the predictions table the script runs properly
and I retrieve the correct results (namely, all the correlations are equal to one, etc.) so this should discard that there is a problem with the biom tables.

However, if I repeat the same exercise but now getting as "observed" one of the tables and as "expected" the same table
after removing a single observation in one of them, the same error came out. So the fact that both tables do not have the same size seems to be the problem because, beyond that, in these tests they are exactly the same table.

Thanks in advance

**Comment by gavinmdouglas** [comment]
@zaneveld do you ever recall coming across the above error with that script?

**Comment by apascualgarcia** [comment]
Hi there,

I think I've solved the issue. The problem is indeed when the two tables do not have the same number of observations, which should be the case most of the times. In that situation, there is a function called `match_biom_tables` which, after the first checkpoint  "_identify ObservationIds unique to each table"_ creates empty matrices if there are observations present in one table and not in the other one. 

Then, in lines 82 to 92, it creates tables with the observations missing to be merged with the observations present, creating two tables with the same sizes for both observed and expected tables. However, in lines 83 and 93, this code:

`        empty_obs_data=[[0]*len(expected_table.ids())]*len(unique_obs_in_observed)`

generates a list, and the next line calling to the biom function Table:

`empty_obs_table=Table(empty_obs_data, unique_obs_in_observed,
expected_table.ids())`

requires a matrix. Therefore, simply transforming the list into a matrix does the work, I simply made:

`      
empty_obs_data=[[0]*len(expected_table.ids())]*len(unique_obs_in_observed) # this is a list    
empty_obs_array=np.asarray(empty_obs_data) # We require an array
empty_obs_table=Table(empty_obs_array, unique_obs_in_observed,
                              expected_table.ids()) # Use the array 
`

Finally, note that in the header I changed

`
#from numpy import array,ravel # Commented
`

by a whole call to numpy: 
`
import numpy as np # new call
`

Please double check that it makes sense, since I do not code in Python.

Cheers,

Alberto

**Comment by gavinmdouglas** [comment]
Hi @apascualgarcia ,

What exact command were you running when you got the original error? I'm looking into making your suggested fix, but I'm unable to reproduce the error. Also, would it be possible to send me the input files you were using to test the script? My email is gavinmdouglas[AT]gmail[DOT]com

Gavin

**Comment by gavinmdouglas** [comment]
Thanks @apascualgarcia I have made the fix based on your troubleshooting! I also confirmed that converting the objects to arrays does not cause the resulting table to be malformed.

Gavin
