### ISSUE TITLE
Normalize OTU Table One or more OTU ids were not found in the precalculated file!

### ISSUE THREAD

**Issue by JiruHan** [picrust/picrust#258]
Hi,

I have just installed picrust on Linux. Whenever I try to run the Normalize OTU Table by function part of picrust, 
normalize_by_copy_number.py
        -i your_otu_table.biom
        -o normalized_otus.biom
I get the following error:
Traceback (most recent call last):
  File "/home/users/allstaff/han.ji/.conda/envs/snp/bin/normalize_by_copy_number.py", line 131, in <module>
    main()
  File "/home/users/allstaff/han.ji/.conda/envs/snp/bin/normalize_by_copy_number.py", line 84, in main
    count_table = convert_precalc_to_biom(count_table_fh, ids_to_load)
  File "/home/users/allstaff/han.ji/.conda/envs/snp/lib/python2.7/site-packages/picrust/util.py", line 103, in convert_precalc_to_biom
    raise ValueError,"One or more OTU ids were not found in the precalculated file!\nAre you using the correct --gg_version?\nExample of (the {0}) unknown OTU ids: {1}".format(len(ids_to_load),', '.join(list(ids_to_load)[:5]))
ValueError: One or more OTU ids were not found in the precalculated file!
Are you using the correct --gg_version?
Example of (the 26813) unknown OTU ids: 11543, 11540, 11546, 11547, 11545

When I check my OTU data, it has no problem.
I don't know how to solve it. Could you please help me solve this problem?😊

Thanks in advance

**Comment by gavinmdouglas** [comment]
Hi @JiruHan , the issue is that PICRUSt1 predictions are only made for 97% Greengenes OTUs. Those IDs must not be in that database which is why you're getting that error.

The easiest solution would be to run PICRUSt2, which you can see here: https://github.com/picrust/picrust2/wiki

**Comment by JiruHan** [comment]
Hi there,

Many thanks for your help.😊
This will help me a lot.
Have a nice day.

Best regards,
Jiru

**Comment by JiruHan** [comment]
Hi there,

I try to run PICRUSt2, and have some problems.
For study_seqs.fna (A FASTA of amplicon sequences variants (ASVs; i.e. your representative sequences)), I'm a little confused about how to generate this file.
Look forward to your reply.
Thank you in advance.

Best regards,
Jiru

**Comment by gavinmdouglas** [comment]
Hi @JiruHan ,

What pipeline are you using for clustering or denoising your 16S sequences? All pipelines should output a file containing the actual representative / clustered 16S sequences for you.

**Comment by JiruHan** [comment]
Hi there,

Many thanks for your help.😊
I have installed the picrust2 from bioconda and source, but when I run the command, it say command not find.
I don’t know how to solve it. Could you please help me?
Thanks in advance.

Best regards,
Jiru

**Comment by JiruHan** [comment]
Hi there,

I have installed the picrust2 successfully.
When I run the picrust2_pipeline.py command, it have errors
(snp) [han.ji@unix500 picrust2]$ picrust2_pipeline.py -s rep.fna -i otu_table2.biom -o picrust2_out_pipeline --threads 1

Error: File existence/permissions problem in trying to open HMM file /home/han.ji/.conda/envs/snp/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm.
HMM file /home/han.ji/.conda/envs/snp/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm not found (nor an .h3

Error running this command:
hmmalign --trim --dna --mapali /home/han.ji/.conda/envs/snp/lib/python3.6/site-packages/default_files/prokaryotic/reference.fna --informat FASTA -o picrust2_out_pipeline/intermediate/place_seqs/query_align.stockholm /home/han.ji/.conda/envs/snp/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm rep.fna

Thanks in advance.

Best regards,
Jiru

**Comment by gavinmdouglas** [comment]
Hi @JiruHan , what operating system are you running and is this on a cluster?

How did you install the instance of PICRUSt2 you're using now?

Is "snp" the name of a conda environment? If so you should deactivate this environment and activate the picrust2 environment if possible.

Gavin

**Comment by JiruHan** [comment]
Hi Gavin,

Many thanks for your reply.😊
The operating system:
[han.ji@unix500 ~]$ uname -a
Linux unix500.wehi.edu.au 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
I don’t think it’s on a cluster.

The following are the steps for my installation of PICRUSt2
module load anaconda3
conda create -n snp
source activate snp
conda install -c conda-forge r-castor
conda install -c bioconda/label/cf201901 picrust2

"snp" is the name of a conda environment.

I've used two ways(install from bioconda and source) to install picrust2 on the website (https://github.com/picrust/picrust2/wiki/Installation) before, but when I installed it and ran it, the command could not be found.

I have two files(fna and biom), do the pipeline only need these two files?

Cheers,
Jiru

**Comment by gavinmdouglas** [comment]
Hmm I'm not sure what the issue is, but I'm also not familiar with your system. If you run ```R``` and then ```library("castor")``` is the castor library loaded?

Yes those are the only 2 input files you will need once the tool is installed correctly.

**Comment by JiruHan** [comment]
Hi Gavin,
Many thanks for your help.😊
I tried it on another computer and I could run, but there were some errors, which were in the attached file.

Thanks in advance!

Best wishes,
Jiru

**Comment by gavinmdouglas** [comment]
The first error is: 

```
STDERR of failed command:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Malformed Fasta input file (/tmp/tmpkjesbnvp/study_seqs_hmmalign.fasta): Empty sequence at line 2.
```

This means there is something wrong with the input FASTA (the sequence is empty).

You also get this warning, which means there was an issue with the installation, but the issue related to this warning probably isn't causing these problems.
```
Warning! ***HDF5 library version mismatched error***
```

Lastly you got this message:
```
Stopping - no ASV ids overlap between input FASTA and sequence abundance table
```

This means that no ids overlap between the input FASTA and BIOM file, which again indicates a problem with input files. The ASV ids need to be the same between the two input files.

Could you post what the first few lines of your input files look like?

**Comment by JiruHan** [comment]
Hi Gavin,

Many thanks for your help and support!😊
The first few lines of my input files are attached to this email.

Best wishes,
Jiru

**Comment by gavinmdouglas** [comment]
Hi @JiruHan , because we're communicating through a github issue I don't think I can see your attachments. Could you send the files to me at gavinmdouglas AT gmail DOT com?


Thanks
