### ISSUE TITLE
'NoneType' object is not iterable in Categorize by function

### ISSUE THREAD

**Issue by panbbq** [picrust/picrust#260]
Hello, I want to use `categorize_by_function.py` to do the function annotation analysis of COG, but I encountered the following problems：

> Traceback (most recent call last):
>   File "/public/software/anaconda2/bin/categorize_by_function.py", line 113, in <module>
>     main()
>   File "/public/software/anaconda2/bin/categorize_by_function.py", line 100, in main
>     one_to_many_md_key=opts.metadata_category)
>   File "/public/software/anaconda2/lib/python2.7/site-packages/biom/table.py", line 2517, in collapse
>     pathway, partition = next(md_iter)
>   File "/public/software/anaconda2/bin/categorize_by_function.py", line 59, in collapse
>     for path in md[category]:
> TypeError: 'NoneType' object is not iterable

I don't know what it means. How to solve it?

**Comment by gavinmdouglas** [comment]
Hi @panbbq,

What version of PICRUSt are you running and did you convert between different BIOM formats before running that command? I think the problem is that there is no metadata in your BIOM table, but the script assumes that a column containing the link between individual COGs and categories is present.

**Comment by panbbq** [comment]
Thank you for your reply.
The version of PICRUSt I am running is 1.1.3
My BIOM table was generated directly through `predict_metagenomes.py`, without any other changes.
Like this (A small part）
![image](https://user-images.githubusercontent.com/49545149/56050109-97c3d680-5d7d-11e9-9004-b64ebbc0308f.png)
The last column is COG_Description,does this matter?

**Comment by gavinmdouglas** [comment]
I'm not an expert on this script, but I believe that is the column that needs to be present. What exact command were you running and what version of BIOM is installed?

**Comment by panbbq** [comment]
Thanks again.
The commands from the resulting OTU table to the functional prediction are as follows:

`normalize_by_copy_number.py -i 05.OTU/otu_table.biom -o 09.Picrust/normalized_otus.biom -c /usr/lib/python2.7/site-packages/picrust/data/16S_13_5_precalculated.tab.gz`
`predict_metagenomes.py --type_of_prediction cog -f -i 09.Picrust/normalized_otus.biom -o 09.Picrust/cog_metagenome_predictions.biom `
`categorize_by_function.py -i 09.Picrust/cog_metagenome_predictions.biom -c COG_Category -l 2  -o 09.Picrust/cog_metagenome_predictions.L2.biom`

The version of BIOM is 2.1.7

**Comment by gavinmdouglas** [comment]
Hi @panbbq,

I think the problem occurs when parsing the tab-delimited file. If you omit the ```-f``` option in ```predict_metagenomes.py``` the ```categorize_by_function.py``` command should work.

Gavin

**Comment by panbbq** [comment]
Hi again.
Although the ` categorize_by_function.py` command can work without the `-f` option in `predict_metagenomes.py`, the file produced in the following command is so small:

> categorize_by_function.py -i 09.Picrust/cog_metagenome_predictions.biom -c COG_Category -l 3  -o 09.Picrust/cog_metagenome_predictions.L3.biom 

File size is less than 50k while the file `cog_metagenome_predictions.biom` is nearly 7000k.
What's more,when I use this command:

> biom convert -i 09.Picrust/cog_metagenome_predictions.L3.biom -o 09.Picrust/cog_metagenome_predictions.L3.txt --table-type='OTU table' --to-tsv

it will have wrong like that:

>   File "/public/software/anaconda2/lib/python2.7/site-packages/biom/table.py", line 1581, in delimited_self
>     raise TableException("Cannot delimit self if I don't have data...")
> biom.exception.TableException: Cannot delimit self if I don't have data...

Thank you very much for your patience.

**Comment by gavinmdouglas** [comment]
I think there are only 2 levels in the COG description which might be why you're running into that problem. Does it work when you use ```-l 2``` rather than ```-l 3```? A smaller file size is definitely expected by the way since there will be many fewer rows in the output.

**Comment by panbbq** [comment]
Thanks a lot.
`-l 2` can work.
