### ISSUE TITLE
Update KEGG metadata in ko_precalculated.biom.gz

### ISSUE THREAD

**Issue by mlangill** [picrust/picrust#77]
Add/replace "KEGG Pathways" metadata in ko_precalculated.biom.gz so that KEGG pathway id, KEGG ortholog definition, and KEGG ortholog id are included. 

Example:

Environmental Information Processing; Signal Transduction; Two-component system; ko02020; phoR, two-component system, OmpR family, phosphate regulon sensor histidine kinase PhoR [EC:2.7.13.3]; K07636

Notes:

1) KEGG Ortholog definitions often contain ';' characters, these will need to be replaced with ',' or ':'.

2) There should always be 6 levels.

3) Since KEGG Orthologs map to more then one KEGG Pathway there can be 1 or more of these 6 level KEGG pathways. These are contained in lists within the BIOM format.

**Comment by willnotburn** [comment]
I'm seeing KEGG metadata in ko_18may2012_precalculated.tab but not in the most recent (and much larger) ko_13_5_precalculated.tab  The latter one just has OTUs and KOs.  Am I not seeing it or is it downloadable from somewhere?

**Comment by mlangill** [comment]
@willnotburn The picrust user list is probably a better place to ask these questions. 

In response, to your question can you try re-downloading the ko_13_5_precalculated.tab file from here:
ftp://ftp.microbio.me/pub/picrust-references/picrust-1.0.0/ko_13_5_precalculated.tab.gz

The ftp server recently changed and I think an older version of this file may have been there before things were synced up. The md5sum for this compressed file should be:
8220d5b3f48af4a86c1542973a365500  ko_13_5_precalculated.tab.gz

Then this file should contain the metadata in the last two lines of the file.
